platform :ios, '14.0'
use_frameworks!

target 'DojoApp' do
  project 'DojoApp'
  pod 'SwiftLint'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'ARCHS'
    end
  end
end